"""Load saved discussion events into analytics records."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class OpinionSnapshot:
    """One agent's opinion text at one round, as recorded by Week 3."""

    agent_id: str
    round_number: int
    phase: str
    opinion_text: str
    created_at: str = ""
    message_id: str = ""
    sequence_number: int = 0
    recipient_ids: tuple[str, ...] = ()
    content_text: str = ""


_BIPOLAR_SEPARATORS = (" versus ", " vs. ", " vs ")


def _bipolar_claim_from_topics(topics: tuple[str, ...]) -> str | None:
    """Turn the first "<A> versus <B>" topic into an actual for/against claim.
    Returns None if no topic matches, so the caller can fall back.
    """
    for topic in topics:
        for sep in _BIPOLAR_SEPARATORS:
            if sep in topic.lower():
                idx = topic.lower().index(sep)
                side_a = topic[:idx].strip().rstrip(".")
                side_b = topic[idx + len(sep):].strip().rstrip(".")
                if side_a and side_b:
                    return f"This team should use {side_b} rather than {side_a}."
    return None


@dataclass(frozen=True)
class DiscussionLog:
    """Validated participants, graph, and per-round messages from one discussion."""

    discussion_id: str
    objective: str
    topics: tuple[str, ...]
    agent_ids: tuple[str, ...]
    edges: tuple[tuple[str, str], ...]
    snapshots: tuple[OpinionSnapshot, ...]

    def proposition(self) -> str:
        """A single bipolar claim describing what stance is measured against.

        """
        bipolar = _bipolar_claim_from_topics(self.topics)
        if bipolar:
            return bipolar
        topic_list = "; ".join(self.topics)
        return f"{self.objective.strip()} (Key topics under debate: {topic_list})"

    def rounds(self) -> list[int]:
        return sorted({s.round_number for s in self.snapshots})

    def snapshots_for(self, agent_id: str) -> list[OpinionSnapshot]:
        return sorted(
            (s for s in self.snapshots if s.agent_id == agent_id),
            key=lambda s: s.round_number,
        )

    def is_stub_only(self) -> bool:
        """True if every snapshot's text is Week 3's deterministic dry-run filler.

        """
        return bool(self.snapshots) and all(
            _looks_like_stub_text(s.opinion_text, s.agent_id) for s in self.snapshots
        )


# Matches Week 3's deterministic dry-run filler, e.g.:
#   "dr_aris initial round 0; received: no neighboring messages."
#   "prof_elena discussion round 2; received: 3 messages."
# This text is auto-generated by a no-LLM/fake backend used for pipeline
# testing, not a real opinion, regardless of which field it's found in.
_STUB_TEXT_PATTERN = re.compile(
    r"^\s*(?P<agent>\S+)\s+(initial|discussion)\s+round\s+\d+;\s+received:", re.IGNORECASE
)


def _looks_like_stub_text(text: str, agent_id: str) -> bool:
    match = _STUB_TEXT_PATTERN.match(text or "")
    return bool(match) and match.group("agent") == agent_id


def _extract_opinion_text(message: dict) -> str:
    """Pick the best available text for stance scoring from a turn_completed message.

    """
    opinion = (message.get("opinion") or "").strip()
    content = (message.get("content") or "").strip()
    if not opinion:
        return content
    if not content:
        return opinion
    # Heuristic: a genuine opinion is rarely dramatically shorter than the
    # full message content; a large gap indicates `opinion` is a stub.
    return content if len(content) > len(opinion) * 2 else opinion


def discover_discussion_files(directory: str | Path) -> list[Path]:
    """Find every discussion .jsonl file under `directory`, sorted by name.

    Used so tasks can run automatically over "whatever discussions exist"
    (for example, `outputs/discussions/`) instead of
    requiring one file path per invocation.
    """
    directory = Path(directory)
    if not directory.is_dir():
        raise NotADirectoryError(f"{directory} is not a directory")
    return sorted(directory.glob("*.jsonl"))


def load_discussion(path: str | Path) -> DiscussionLog:
    """Parse a saved Qubettera discussion JSONL file."""
    path = Path(path)
    discussion_id = ""
    objective = ""
    topics: tuple[str, ...] = ()
    agent_ids: list[str] = []
    edges: list[tuple[str, str]] = []
    snapshots: list[OpinionSnapshot] = []
    started = completed = False
    expected_rounds: int | None = None
    seen_message_ids: set[str] = set()
    seen_turns: set[tuple[str, int]] = set()

    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            raw_line = raw_line.strip()
            if not raw_line:
                continue
            try:
                event = json.loads(raw_line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_number} is not valid JSON") from exc
            if not isinstance(event, dict):
                raise ValueError(f"{path}:{line_number} must be a JSON object")

            kind = event.get("event")

            if kind == "discussion_started":
                if started:
                    raise ValueError(f"{path}:{line_number} has duplicate discussion_started")
                started = True
                discussion_id = str(event.get("discussion_id") or "")
                config = event.get("config", {})
                if not isinstance(config, dict) or not isinstance(config.get("brief"), dict):
                    raise ValueError(f"{path}:{line_number} has invalid discussion config")
                brief = config.get("brief", {})
                objective = brief.get("objective", "")
                raw_topics = brief.get("topics", ())
                graph = event.get("graph", {})
                if (not isinstance(graph, dict) or not isinstance(graph.get("nodes"), list)
                    or not isinstance(graph.get("edges", []), list)
                    or not isinstance(raw_topics, (list, tuple))
                    or any(not isinstance(topic, str) for topic in raw_topics)):
                    raise ValueError(f"{path}:{line_number} has invalid graph or topics")
                topics = tuple(raw_topics)
                agent_ids = graph["nodes"]
                expected_rounds = config.get("num_rounds")
                if (not discussion_id or not isinstance(objective, str) or not objective.strip()
                    or not agent_ids or not all(isinstance(a, str) and a for a in agent_ids)
                    or len(set(agent_ids)) != len(agent_ids)):
                    raise ValueError(f"{path}:{line_number} has invalid discussion ID or graph nodes")
                if expected_rounds is not None and (type(expected_rounds) is not int or expected_rounds < 0):
                    raise ValueError(f"{path}:{line_number} has invalid num_rounds")
                for edge in graph.get("edges", []):
                    if not isinstance(edge, (list, tuple)) or len(edge) != 2:
                        raise ValueError(f"{path}:{line_number} has invalid graph edge {edge!r}")
                    src, dst = edge
                    if src not in agent_ids or dst not in agent_ids:
                        raise ValueError(f"{path}:{line_number} has edge outside graph nodes")
                    edges.append((src, dst))
                if len(set(edges)) != len(edges):
                    raise ValueError(f"{path}:{line_number} has duplicate graph edges")
                continue

            if kind == "turn_completed":
                if not started or completed:
                    raise ValueError(f"{path}:{line_number} has turn outside discussion")
                message = event.get("message", {})
                if not isinstance(message, dict):
                    raise ValueError(f"{path}:{line_number} has invalid message")
                if message.get("phase") == "synthesis":
                    continue
                sender_id = message.get("sender_id")
                message_id = message.get("message_id")
                round_number = message.get("round_number")
                recipients = message.get("recipient_ids")
                if not isinstance(message.get("opinion", ""), str) or not isinstance(message.get("content", ""), str):
                    raise ValueError(f"{path}:{line_number} has invalid message text")
                opinion_text = _extract_opinion_text(message)
                if (sender_id not in agent_ids or not isinstance(message_id, str) or not message_id
                    or type(round_number) is not int or round_number < 0
                    or not isinstance(recipients, list) or any(r not in agent_ids for r in recipients)
                    or not opinion_text or not isinstance(message.get("content"), str)):
                    raise ValueError(f"{path}:{line_number} has invalid participant turn")
                if (round_number == 0 and message.get("phase") != "initial") or (
                    round_number > 0 and message.get("phase") != "discussion"
                ):
                    raise ValueError(f"{path}:{line_number} has invalid turn phase")
                if expected_rounds is not None and round_number > expected_rounds:
                    raise ValueError(f"{path}:{line_number} exceeds configured discussion rounds")
                if any((sender_id, recipient) not in edges for recipient in recipients):
                    raise ValueError(f"{path}:{line_number} routes outside the graph")
                if message.get("discussion_id", discussion_id) != discussion_id:
                    raise ValueError(f"{path}:{line_number} has mismatched discussion ID")
                if message_id in seen_message_ids or (sender_id, round_number) in seen_turns:
                    raise ValueError(f"{path}:{line_number} has duplicate message or participant round")
                sequence_number = message.get("sequence_number", 0)
                if type(sequence_number) is not int or sequence_number < 0:
                    raise ValueError(f"{path}:{line_number} has invalid sequence number")
                seen_message_ids.add(message_id)
                seen_turns.add((sender_id, round_number))
                snapshots.append(
                    OpinionSnapshot(
                        agent_id=sender_id,
                        round_number=round_number,
                        phase=message.get("phase", ""),
                        opinion_text=opinion_text,
                        created_at=message.get("created_at", ""),
                        message_id=message_id,
                        sequence_number=sequence_number,
                        recipient_ids=tuple(recipients),
                        content_text=message["content"],
                    )
                )
                continue

            if kind == "discussion_completed":
                if not started or completed or event.get("discussion_id", discussion_id) != discussion_id:
                    raise ValueError(f"{path}:{line_number} has invalid completion event")
                completed = True

            # "discussion_completed" and any future event types carry
            # nothing Tasks 1â€“3 need, so they are intentionally ignored.

    if not started or not completed:
        raise ValueError(f"{path} is not a completed discussion log")
    if not snapshots:
        raise ValueError(f"{path} contained no turn_completed events to score.")
    rounds = range((expected_rounds + 1) if expected_rounds is not None else (max(s.round_number for s in snapshots) + 1))
    missing = [(agent, round_number) for round_number in rounds for agent in agent_ids
               if (agent, round_number) not in seen_turns]
    if missing:
        raise ValueError(f"{path} has incomplete participant rounds: {missing[:5]}")

    log = DiscussionLog(
        discussion_id=discussion_id,
        objective=objective,
        topics=topics,
        agent_ids=tuple(agent_ids),
        edges=tuple(edges),
        snapshots=tuple(snapshots),
    )
    if any(_looks_like_stub_text(s.opinion_text, s.agent_id) for s in log.snapshots):
        raise ValueError(
            f"{path} contains only deterministic dry-run filler text (no real LLM "
            "opinions to score) â€” this discussion appears to have been generated "
            "with a fake/no-LLM Week 3 backend."
        )
    return log

